name: elder_quest

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  go_router: ^14.6.2
  share_plus: ^12.0.1
  screenshot: ^3.0.0
  google_fonts: ^6.2.1
  just_audio: ^0.9.38
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
    - assets/json/
  fonts:
    - family: Idiqlat
      fonts:
        - asset: assets/fonts/Idiqlat-2.000/Idiqlat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Idiqlat-2.000/Idiqlat-Light.ttf
          weight: 300
        - asset: assets/fonts/Idiqlat-2.000/Idiqlat-Regular.ttf
          weight: 400
